API_ENDPOINT = "/api"

### AUTH ENDPOINTS
AUTH_ENDPOINT = API_ENDPOINT + "/auth"
LOGIN_ENDPOINT = "/login"
LOGOUT_ENDPOINT = "/logout"
REGISTER_ENDPOINT = "/register"

### LISTS ENDPOINTS (Prepend with LISTS_ENDPOINT)
LISTS_ENDPOINT = API_ENDPOINT + "/lists"
CREATE_LIST_ENDPOINT = "/"

GET_ALL_LISTS_ENDPOINT = "/all"
GET_LIST_ENDPOINT = "/<int:list_id>"

EDIT_LIST_ENDPOINT = GET_LIST_ENDPOINT + "/edit"
DELETE_LIST_ENDPOINT = GET_LIST_ENDPOINT + "/delete"

### TASKS ENDPOINTS (Prepend with TASKS_ENDPOINT)
TASKS_ENDPOINT = LISTS_ENDPOINT + "/<int:list_id>/tasks"
GET_TASKS_ENDPOINT = "/all"
CREATE_TASK_ENDPOINT = "/"

GET_TASK_ENDPOINT = "/<int:task_id>"
UPDATE_TASK_STATUS_ENDPOINT = GET_TASK_ENDPOINT + "/status"
DELETE_TASK_ENDPOINT = GET_TASK_ENDPOINT + "/delete"

EDIT_TASK_ENDPOINT = GET_TASK_ENDPOINT + "/edit"
MOVE_TASK_ENDPOINT = GET_TASK_ENDPOINT + "/move"

GET_SUBTASKS_ENDPOINT = "/<int:parent_id>"
CREATE_SUBTASK_ENDPOINT = GET_SUBTASKS_ENDPOINT + "/subtasks"
